## pandas-series-dataframe

In [ ]:
# 모듈 임포트
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
# Series
s = pd.Series([1, 3])
s

0    1
1    3
dtype: int64

In [ ]:
# Series with index
s = pd.Series([1, 3], index=["a", "b"])
s

a    1
b    3
dtype: int64

In [ ]:
# DataFrame
df = pd.DataFrame({"A": [1, 2], "B": ["a", "b"], "C": [2.3, 1.2]})
df

   A  B    C
0  1  a  2.3
1  2  b  1.2

In [ ]:
df["A"]

0    1
1    2
Name: A, dtype: int64

In [ ]:
type(df["A"])

pandas.core.series.Series

## pandas-funcs-1

In [ ]:
import pandas as pd

In [ ]:
# 샘플 데이터 - 1990년 California 주택 데이터
csv_file_url = "https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"
df = pd.read_csv(csv_file_url, sep=",")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# to_csv
df.to_csv("./my-housing-data.csv", sep="|", index=False)
!ls

my-housing-data.csv  sample_data

In [ ]:
# head
df.head(n=2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [ ]:
# iloc
df.iloc[:2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [ ]:
df.iloc[[1, 2], [0, 1]]

   longitude  latitude
1    -114.47     34.40
2    -114.56     33.69

In [ ]:
df.iloc[:, 1:3]

       latitude  housing_median_age
0         34.19                15.0
1         34.40                19.0
2         33.69                17.0
3         33.64                14.0
4         33.57                20.0
...         ...                 ...
16995     40.58                52.0
16996     40.69                36.0
16997     41.84                17.0
16998     41.80                19.0
16999     40.54                52.0

[17000 rows x 2 columns]

In [ ]:
# loc
df.loc[0, "median_house_value"]

np.float64(66900.0)

In [ ]:
# boolean 인덱싱
mask = df["housing_median_age"] < 17
mask

0         True
1        False
2        False
3         True
4        False
         ...
16995    False
16996    False
16997    False
16998    False
16999    False
Name: housing_median_age, Length: 17000, dtype: bool

In [ ]:
print(df.loc[mask, :])

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
3        -114.57     33.64                14.0       1501.0           337.0
10       -114.60     33.62                16.0       3741.0           801.0
14       -114.63     32.76                15.0       1448.0           378.0
23       -114.98     33.82                15.0        644.0           129.0
...          ...       ...                 ...          ...             ...
16914    -124.09     40.92                12.0       2497.0           491.0
16957    -124.16     41.74                15.0       2715.0           569.0
16976    -124.17     40.75                13.0       2171.0           339.0
16983    -124.19     41.78                15.0       3140.0           714.0
16991    -124.23     41.75                11.0       3159.0           616.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
3           515.0       226.0         3.1917             73400.0
10         2434.0       824.0         2.6797             86500.0
14          949.0       300.0         0.8585             45000.0
23          137.0        52.0         3.2097             71300.0
...           ...         ...            ...                 ...
16914      1153.0       462.0         2.8182            126900.0
16957      1532.0       530.0         2.1829             69500.0
16976       951.0       353.0         4.8516            116100.0
16983      1645.0       640.0         1.6654             74600.0
16991      1343.0       479.0         2.4805             73200.0

[3360 rows x 9 columns]

In [ ]:
# 여러 개의 조건 설정
and_mask = (df["housing_median_age"] < 17) \
            & (df["median_house_value"] < 70000)
df.loc[and_mask, :]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0
55,-115.52,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0
58,-115.52,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0
59,-115.53,34.91,12.0,807.0,199.0,246.0,102.0,2.5391,40000.0
...,...,...,...,...,...,...,...,...,...
16513,-122.65,41.72,15.0,3643.0,801.0,1784.0,743.0,1.8533,57500.0
16643,-122.74,39.71,16.0,255.0,73.0,85.0,38.0,1.6607,14999.0
16814,-123.21,40.51,16.0,241.0,84.0,152.0,61.0,1.3750,48800.0
16834,-123.32,40.43,15.0,661.0,146.0,131.0,57.0,0.4999,56700.0
16957,-124.16,41.74,15.0,2715.0,569.0,1532.0,530.0,2.1829,69500.0

In [ ]:
or_mask = (df["total_rooms"] > 6000) | (df["total_bedrooms"] > 1500)
df.loc[or_mask, :]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
133,-116.06,34.15,15.0,10377.0,2331.0,4507.0,1807.0,2.2466,66800.0
135,-116.09,34.15,13.0,9444.0,1997.0,4166.0,1482.0,2.6111,65600.0
168,-116.24,33.71,10.0,9033.0,2224.0,5525.0,1845.0,2.7598,95000.0
172,-116.26,33.65,3.0,7437.0,1222.0,574.0,302.0,10.2948,382400.0
...,...,...,...,...,...,...,...,...,...
16568,-122.69,38.37,8.0,6322.0,1001.0,2969.0,1043.0,4.8233,214000.0
16619,-122.72,38.58,4.0,7042.0,1100.0,2936.0,1043.0,5.0555,240800.0
16652,-122.75,38.54,6.0,6719.0,1016.0,2699.0,997.0,5.4886,254200.0
16679,-122.79,38.48,7.0,6837.0,1417.0,3468.0,1405.0,3.1662,191000.0
16692,-122.82,38.55,8.0,6190.0,1088.0,2967.0,1000.0,3.8616,195100.0