## preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 결측치 처리 - 확인
url = "http://support.sas.com/documentation/onlinedoc/viya/exampledatasets/hmeq.csv"
df = pd.read_csv(url)
df.isna().sum()

BAD           0
LOAN          0
MORTDUE     518
VALUE       112
REASON      252
JOB         279
YOJ         515
DEROG       708
DELINQ      580
CLAGE       308
NINQ        510
CLNO        222
DEBTINC    1267
dtype: int64

In [ ]:
# 결측치 처리 방법 - 제거
print(f"Length before dropna: {len(df)}")
df_dropped = df.dropna()
print(f"Length after dropna: {len(df_dropped)}")

Length before dropna: 5960
Length after dropna: 3364

In [ ]:
# 결측치 처리 방법 - 치환
categorical_columns = ['REASON', 'JOB']
numeric_columns = [col for col in df.columns \
                    if col not in categorical_columns and col != 'BAD']

for col in categorical_columns:
    # 최빈값으로 결측치 대체
    # inplace 옵션으로 새 데이터프레임을 반환하지 않고 해당 데이터프레임에 직접 연산 수행
    df[col].fillna(df[col].value_counts().idxmax(), inplace=True)

for col in numeric_columns:
    # 중간값으로 결측치 대체
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipython-input-3948280725.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].value_counts().idxmax(), inplace=True)
/tmp/ipython-input-3948280725.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].value_counts().idxmax(), inplace=True)
/tmp/ipython-input-3948280725.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
# 표준화
# 비교를 위한 head 출력
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,HomeImp,Other,10.5,0.0,0.0,94.366667,1.0,9.0,34.818262
1,1,1300,70053.0,68400.0,HomeImp,Other,7.0,0.0,2.0,121.833333,0.0,14.0,34.818262
2,1,1500,13500.0,16700.0,HomeImp,Other,4.0,0.0,0.0,149.466667,1.0,10.0,34.818262
3,1,1500,65019.0,89235.5,DebtCon,Other,7.0,0.0,0.0,173.466667,1.0,20.0,34.818262
4,0,1700,97800.0,112000.0,HomeImp,Office,3.0,0.0,0.0,93.333333,0.0,14.0,34.818262

In [ ]:
# 수치형 변수에 대해서만 표준화(평균값을 빼준 뒤 표준편차로 나눠줌)
for col in numeric_columns:
    df[col] = (df[col] - df[col].mean()) / df[col].std()
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,-1.562168,-1.107827,-1.099279,HomeImp,Other,0.240217,-0.280953,-0.375911,-1.017940,-0.102871,-1.230775,0.106954
1,1,-1.544323,-0.069280,-0.582745,HomeImp,Other,-0.241915,-0.280953,1.477217,-0.689292,-0.707515,-0.728328,0.106954
2,1,-1.526478,-1.398290,-1.491845,HomeImp,Other,-0.655171,-0.280953,-0.375911,-0.358650,-0.102871,-1.130286,0.106954
3,1,-1.526478,-0.187580,-0.216371,DebtCon,Other,-0.241915,-0.280953,-0.375911,-0.071482,-0.102871,-0.125392,0.106954
4,0,-1.508633,0.582782,0.183923,HomeImp,Office,-0.792923,-0.280953,-0.375911,-1.030305,-0.707515,-0.728328,0.106954

In [ ]:
# 범주형(+ 이산형) 변수 처리
encoded_categorical_df = pd.get_dummies(df[categorical_columns])

# 범주형(+ 이산형) 변수를 제외한 뒤, one-hot encoding을 수행한 새 컬럼을 뒤에 붙임
df_wo_categorical = df.drop(categorical_columns, axis=1)
df = pd.concat([df_wo_categorical, encoded_categorical_df], axis=1)
df.head()

,BAD,LOAN,MORTDUE,VALUE,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC,REASON_DebtCon,REASON_HomeImp,JOB_Mgr,JOB_Office,JOB_Other,JOB_ProfExe,JOB_Sales,JOB_Self
0,1,-1.562168,-1.107827,-1.099279,0.240217,-0.280953,-0.375911,-1.017940,-0.102871,-1.230775,0.106954,False,True,False,False,True,False,False,False
1,1,-1.544323,-0.069280,-0.582745,-0.241915,-0.280953,1.477217,-0.689292,-0.707515,-0.728328,0.106954,False,True,False,False,True,False,False,False
2,1,-1.526478,-1.398290,-1.491845,-0.655171,-0.280953,-0.375911,-0.358650,-0.102871,-1.130286,0.106954,False,True,False,False,True,False,False,False
3,1,-1.526478,-0.187580,-0.216371,-0.241915,-0.280953,-0.375911,-0.071482,-0.102871,-0.125392,0.106954,True,False,False,False,True,False,False,False
4,0,-1.508633,0.582782,0.183923,-0.792923,-0.280953,-0.375911,-1.030305,-0.707515,-0.728328,0.106954,False,True,False,True,False,False,False,False

## sklearn-model

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss, accuracy_score

In [ ]:
## 전처리 - 이전 강의에서 한 것 복사
# 결측치 처리 - 확인
url = "http://support.sas.com/documentation/onlinedoc/viya/exampledatasets/hmeq.csv"
df = pd.read_csv(url)

# 결측치 처리 방법 - 치환
categorical_columns = ['REASON', 'JOB']
numeric_columns = [col for col in df.columns \
                    if col not in categorical_columns and col != 'BAD']

for col in categorical_columns:
    # 최빈값으로 결측치 대체
    # inplace 옵션으로 새 데이터프레임을 반환하지 않고 해당 데이터프레임에 직접 연산 수행
    df[col].fillna(df[col].value_counts().idxmax(), inplace=True)

for col in numeric_columns:
    # 중간값으로 결측치 대체
    df[col].fillna(df[col].median(), inplace=True)

# 수치형 변수에 대해서만 표준화(평균값을 빼준 뒤 표준편차로 나눠줌)
for col in numeric_columns:
    df[col] = (df[col] - df[col].mean()) / df[col].std()

# 범주형(+ 이산형) 변수 처리
encoded_categorical_df = pd.get_dummies(df[categorical_columns])

# 범주형(+ 이산형) 변수를 제외한 뒤, one-hot encoding을 수행한 새 컬럼을 뒤에 붙임
df_wo_categorical = df.drop(categorical_columns, axis=1)
df = pd.concat([df_wo_categorical, encoded_categorical_df], axis=1)
df.head()

/tmp/ipython-input-2056855089.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].value_counts().idxmax(), inplace=True)
/tmp/ipython-input-2056855089.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].value_counts().idxmax(), inplace=True)
/tmp/ipython-input-2056855089.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

,BAD,LOAN,MORTDUE,VALUE,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC,REASON_DebtCon,REASON_HomeImp,JOB_Mgr,JOB_Office,JOB_Other,JOB_ProfExe,JOB_Sales,JOB_Self
0,1,-1.562168,-1.107827,-1.099279,0.240217,-0.280953,-0.375911,-1.017940,-0.102871,-1.230775,0.106954,False,True,False,False,True,False,False,False
1,1,-1.544323,-0.069280,-0.582745,-0.241915,-0.280953,1.477217,-0.689292,-0.707515,-0.728328,0.106954,False,True,False,False,True,False,False,False
2,1,-1.526478,-1.398290,-1.491845,-0.655171,-0.280953,-0.375911,-0.358650,-0.102871,-1.130286,0.106954,False,True,False,False,True,False,False,False
3,1,-1.526478,-0.187580,-0.216371,-0.241915,-0.280953,-0.375911,-0.071482,-0.102871,-0.125392,0.106954,True,False,False,False,True,False,False,False
4,0,-1.508633,0.582782,0.183923,-0.792923,-0.280953,-0.375911,-1.030305,-0.707515,-0.728328,0.106954,False,True,False,True,False,False,False,False

In [ ]:
# 개발 - 검증 - 테스트 데이터 분리
df_x = df.drop(['BAD'], axis=1)
df_y = df['BAD']
# rule-of-thumb -> training : validation : test = 0.6 : 0.2 : 0.2
# 개발 데이터셋 생성
X_train, X_val, y_train, y_val = train_test_split(df_x.values, df_y.values, test_size=0.4)
# 검증, 테스트 데이터셋 생성
X_val, X_test, y_val, y_test = train_test_split(X_val, y_val, test_size=0.5)
print(f"개발 셋 길이: {len(X_train)}, 검증 셋 길이: {len(X_val)}, 테스트 셋 길이: {len(X_test)}")

개발 셋 길이: 3576, 검증 셋 길이: 1192, 테스트 셋 길이: 1192

In [ ]:
# 개발 데이터로 모형 적합
# 로지스틱 회귀 모델
log_clf = LogisticRegression(penalty='l1', solver='liblinear', random_state=42)
log_clf.fit(X_train, y_train)

LogisticRegression(penalty='l1', random_state=42, solver='liblinear')

In [ ]:
# 검증 데이터로 적합된 모형 평가
val_predictions = log_clf.predict(X_val)
val_probs = log_clf.predict_proba(X_val)

val_acc = accuracy_score(y_val, val_predictions)
val_loss = log_loss(y_val, val_probs)

print(f"Val. Accuracy: {val_acc:.2%}, Val. Loss: {val_loss}")

Val. Accuracy: 83.39%, Val. Loss: 0.401170680508278

In [ ]:
test_predictions = log_clf.predict(X_test)
test_probs = log_clf.predict_proba(X_test)

test_acc = accuracy_score(y_test, test_predictions)
test_loss = log_loss(y_test, test_probs)

print(f"Test Accuracy: {test_acc:.2%}, Test Loss: {test_loss}")

Test Accuracy: 82.05%, Test Loss: 0.42058885414249253